name: Test Pipeline

on:
  push:
    branches: [main]

jobs:
  test-endpoints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - name: Configurar variables de entorno
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar tests de endpoints o rutas
        run: npm test -- "tests/routes.test.js"

  test-partida:
    needs: test-endpoints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar tests de la clase Partida
        run: npm test -- "tests/partida.test.js"
