on:
  push:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar tests
        run: npm test -- "test/Partida.test.js"
